### ISSUE TITLE
Autopublish option

### ISSUE THREAD

**Issue by nicolas-cusan** [arillo/silverstripe-elements#4]
It would be nice to have an option, set through `config.yml`, that allows to publish elements by saving them instead of having to save the parent page to publish.

Rough sketch:

Global option:
```yml
ElementBase:
  #Automatically publish all `Element`s when they are saved
  autopublish: true
```

Per-relationship option:
```yml
SlideshowElement:
  #Automatically publish all `ImageElement`s that are children of `SlideshowElement`
  autopublish: true
  element_relations:
    Slides:
      - ImageElement
```

A possible caveat (or maybe not) of the per-relationship setting would be that all `element_relations` would inherit the `autopublish` option.
