### ISSUE TITLE
Feature: Allow multipe inherited relations

### ISSUE THREAD

**Issue by bumbus** [arillo/silverstripe-elements#44]
`element_relations_inherit_from` should be expanded to also support arrays, e.g.:

```
# current functionality, should still work
SectionsPage:
  element_relations_inherit_from: CommonSections

# new functionality
SectionsPage:
  element_relations_inherit_from:
    - CommonSections
    - Banners
```
