### ISSUE TITLE
Bulk Editing & Batch Uploading

### ISSUE THREAD

**Issue by nicolas-cusan** [arillo/silverstripe-elements#5]
It would be great to be able to use this module https://github.com/colymba/GridFieldBulkEditingTools and define via `config.yml` on what models it should be used. As the `ElementBase` fields are defined on a project basis, bulk uploading might not always be relevant.

```
SlideshowElement:
  bulk_upload: true
  bulk_edit:
    - delete
  element_relations:
    Slides:
      - ImageElement
```
